# Generated by Django 2.0.13 on 2019-04-28 01:23

from django.db import migrations, models
import django.db.models.deletion
import streams.custom_blocks
import wagtail.contrib.routable_page.models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdaptPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('content', wagtail.core.fields.StreamField([('free_carousel', wagtail.core.blocks.StructBlock([('pages', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(max_length=25, required=False)), ('sub_title', wagtail.core.blocks.TextBlock(max_length=50, required=False))])))])), ('title_and_Subtitle', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add your title', required=False)), ('sub_title', wagtail.core.blocks.CharBlock(help_text='Add your sub-title', required=False))])), ('full_richtext', streams.custom_blocks.RichtextBlock()), ('limited_richtext', streams.custom_blocks.LimitedRichtextBlock()), ('left_media_list', wagtail.core.blocks.StructBlock([('mediaList', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(required=True)), ('paragraph', wagtail.core.blocks.TextBlock(required=True))])))])), ('alt_small_media_list', wagtail.core.blocks.StructBlock([('mediaList', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('r_image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('r_title', wagtail.core.blocks.CharBlock(max_length=20, required=False)), ('r_paragraph', wagtail.core.blocks.TextBlock(max_length=250, min_length=50, required=False)), ('l_image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('l_title', wagtail.core.blocks.CharBlock(required=False)), ('l_paragraph', wagtail.core.blocks.TextBlock(help_text='Looks bad without at least 200 characters', max_length=350, min_length=150, required=False))])))])), ('embeding', streams.custom_blocks.EmbededBlock()), ('cards', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add your title', required=False)), ('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(max_length=40, required=True)), ('text_body', wagtail.core.blocks.TextBlock(max_length=350, required=True)), ('local_page_button', wagtail.core.blocks.PageChooserBlock(help_text='(optional) - this is priority button', required=False)), ('url_button', wagtail.core.blocks.URLBlock(help_text='(optional) - button above used first', required=False))])))])), ('alternating_featurettes', wagtail.core.blocks.StructBlock([('mediaList', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('r_image', wagtail.images.blocks.ImageChooserBlock(help_text='must be at least 445x445', required=True)), ('r_title', wagtail.core.blocks.CharBlock(required=False)), ('r_sub_title', wagtail.core.blocks.CharBlock(max_length=20, required=False)), ('r_paragraph', wagtail.core.blocks.TextBlock(max_length=450, min_length=50, required=False)), ('l_image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('l_title', wagtail.core.blocks.CharBlock(required=False)), ('l_sub_title', wagtail.core.blocks.CharBlock(required=False)), ('l_paragraph', wagtail.core.blocks.TextBlock(help_text='might look with less than 200 characters', max_length=450, min_length=50, required=False))])))]))], blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
    ]
