# Generated by Django 2.1.7 on 2019-04-04 16:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0003_capitalizeverbose'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('blog', '0002_articlepage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticlePage',
            new_name='BlogFocusPage',
        ),
        migrations.RenameModel(
            old_name='BlogPage',
            new_name='BlogListingPage',
        ),
    ]
