# Generated by Django 2.1.7 on 2019-04-11 06:23

import blog.blog_blocks
from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190404_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogfocuspage',
            name='content',
            field=wagtail.core.fields.StreamField([('title_and_text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add your title', required=True)), ('text', wagtail.core.blocks.TextBlock(help_text='Add additional text', required=True))])), ('full_richtext', blog.blog_blocks.RichtextBlock()), ('limited_richtext', blog.blog_blocks.LimitedRichtextBlock())], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogfocuspage',
            name='custom_title',
            field=models.CharField(blank=True, help_text='Type in the title for the blog article title', max_length=100),
        ),
        migrations.AddField(
            model_name='bloglistingpage',
            name='custom_title',
            field=models.CharField(blank=True, help_text='type in the title for the blog listing page', max_length=100),
        ),
    ]
