# Generated by Django 2.1.7 on 2019-04-11 06:51

import blog.blog_blocks
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190411_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogfocuspage',
            name='content',
            field=wagtail.core.fields.StreamField([('title_and_text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add your title', required=True)), ('sub_title', wagtail.core.blocks.CharBlock(help_text='Add your sub-title', required=True))])), ('full_richtext', blog.blog_blocks.RichtextBlock()), ('limited_richtext', blog.blog_blocks.LimitedRichtextBlock())], blank=True, null=True),
        ),
    ]
