# Generated by Django 2.1.7 on 2019-04-13 19:26

import blog.blog_blocks
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('blog', '0006_blogfocuspage_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloglistingpage',
            name='blog_listing_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='bloglistingpage',
            name='content',
            field=wagtail.core.fields.StreamField([('title_and_text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add your title', required=True)), ('sub_title', wagtail.core.blocks.CharBlock(help_text='Add your sub-title', required=True))])), ('full_richtext', blog.blog_blocks.RichtextBlock()), ('limited_richtext', blog.blog_blocks.LimitedRichtextBlock())], blank=True, null=True),
        ),
    ]
