# Generated by Django 2.1.7 on 2019-04-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190413_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloglistingpage',
            name='content',
        ),
        migrations.AddField(
            model_name='blogfocuspage',
            name='summary',
            field=models.CharField(blank=True, help_text='This summary is displayed in the blog listing page', max_length=300),
        ),
    ]
