# Generated by Django 2.1.7 on 2019-04-14 00:44

import blog.blog_blocks
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190414_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogfocuspage',
            name='content',
            field=wagtail.core.fields.StreamField([('title_and_text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add your title', required=True)), ('sub_title', wagtail.core.blocks.CharBlock(help_text='Add your sub-title', required=True))])), ('full_richtext', blog.blog_blocks.RichtextBlock()), ('limited_richtext', blog.blog_blocks.LimitedRichtextBlock()), ('embeding', wagtail.embeds.blocks.EmbedBlock())], blank=True, null=True),
        ),
    ]
