# Generated by Django 2.1.7 on 2019-04-14 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190414_0131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloglistingpage',
            old_name='blog_listing_image',
            new_name='blog_listing_banner',
        ),
    ]
