# Generated by Django 2.1.7 on 2019-04-14 08:13

import blog.blog_blocks
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20190414_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogfocuspage',
            name='required_content',
            field=wagtail.core.fields.StreamField([('title_and_text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add your title', required=True)), ('sub_title', wagtail.core.blocks.CharBlock(help_text='Add your sub-title', required=True))]))], null=True),
        ),
        migrations.AlterField(
            model_name='blogfocuspage',
            name='content',
            field=wagtail.core.fields.StreamField([('full_richtext', blog.blog_blocks.RichtextBlock()), ('limited_richtext', blog.blog_blocks.LimitedRichtextBlock()), ('embeding', blog.blog_blocks.EmbededBlock()), ('card_block', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add your title', required=False)), ('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(max_length=40, required=True)), ('text_body', wagtail.core.blocks.TextBlock(max_length=350, required=True)), ('local_page_button', wagtail.core.blocks.PageChooserBlock(help_text='(optional) - this is priority button', required=False)), ('url_button', wagtail.core.blocks.URLBlock(help_text='(optional) - above button used first', required=False))])))]))], blank=True, null=True),
        ),
    ]
