# Generated by Django 2.0.13 on 2019-04-24 02:46

import blog.blog_blocks
from django.db import migrations, models
import django.db.models.deletion
import wagtail.contrib.routable_page.models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('blog', '0017_auto_20190420_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('content', wagtail.core.fields.StreamField([('title_and_Subtitle', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add your title', required=False)), ('sub_title', wagtail.core.blocks.CharBlock(help_text='Add your sub-title', required=False))])), ('full_richtext', blog.blog_blocks.RichtextBlock()), ('limited_richtext', blog.blog_blocks.LimitedRichtextBlock()), ('embeding', blog.blog_blocks.EmbededBlock()), ('card_block', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add your title', required=False)), ('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(max_length=40, required=True)), ('text_body', wagtail.core.blocks.TextBlock(max_length=350, required=True)), ('local_page_button', wagtail.core.blocks.PageChooserBlock(help_text='(optional) - this is priority button', required=False)), ('url_button', wagtail.core.blocks.URLBlock(help_text='(optional) - button above used first', required=False))])))]))], blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
    ]
