# Generated by Django 2.0.8 on 2019-04-11 01:08

from django.db import migrations, models
import django_google_maps.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=500)),
                ('date', models.DateField(blank=True)),
                ('start_time', models.TimeField(blank=True)),
                ('end_time', models.TimeField(blank=True)),
                ('address', django_google_maps.fields.AddressField(max_length=100)),
                ('geolocation', django_google_maps.fields.GeoLocationField(blank=True, max_length=100)),
            ],
        ),
    ]
