# Generated by Django 2.1.7 on 2019-02-24 19:05

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='more',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
