# Generated by Django 2.1.7 on 2019-02-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190226_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='test_field',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
