# Generated by Django 2.1.7 on 2019-03-03 23:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailforms', '0003_capitalizeverbose'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0008_testpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestPage',
            new_name='DemoPage',
        ),
    ]
