# Generated by Django 2.1.7 on 2019-03-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_aboutpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='body',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
