# Generated by Django 2.1.7 on 2019-03-05 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20190305_0841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutpage',
            old_name='bodyj',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='aboutpage',
            old_name='extraj',
            new_name='extra',
        ),
        migrations.RenameField(
            model_name='aboutpage',
            old_name='morej',
            new_name='more',
        ),
        migrations.RenameField(
            model_name='aboutpage',
            old_name='test_fieldj',
            new_name='test_field',
        ),
    ]
