# Generated by Django 2.1.7 on 2019-03-12 01:22

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20190305_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='testing',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
