# Generated by Django 2.1.7 on 2019-03-12 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_aboutpage_testing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='testing',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=models.TextField(max_length=255),
        ),
    ]
