# Generated by Django 2.1.7 on 2019-03-12 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20190312_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='carousel_1_body',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='carousel_1_header',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='carousel_2_body',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='carousel_2_header',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
