# Generated by Django 2.1.7 on 2019-03-12 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20190312_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='carousel_1_header',
        ),
    ]
