# Generated by Django 2.1.7 on 2019-03-12 01:32

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_homepage_carousel_1_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='carousel_1_header',
            field=wagtail.core.fields.RichTextField(blank=True, max_length=255),
        ),
    ]
