# Generated by Django 2.1.7 on 2019-03-12 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_homepage_carousel_1_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='carousel_1_header',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
