# Generated by Django 2.1.7 on 2019-03-12 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20190312_0145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='more',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='test_field',
        ),
        migrations.AddField(
            model_name='homepage',
            name='carousel_3_body',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='carousel_3_header',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='carousel_1_body',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='carousel_2_body',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='carousel_2_header',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
